LLAMA3_LAW_PATH = "/home/paul/.cache/huggingface/models/models--unsloth--llama-3-8b-Instruct-lawdata"
LLAMA3_LAW_AWQ_PATH = "/home/paul/.cache/huggingface/models/Llama3_CN_Law_Merged_awq"
DEEPSEEK_32B_PATH = "/home/paul/.cache/huggingface/models/DeepSeek-R1-Distill-Qwen-32B"
LLAMA3_LAW_VLLM_ID = "llama-3-8b-Instruct-lawdata"
LLAMA3_LAW_VLLM_ID = "llama-3-8b-Instruct-lawdata"
QWEN_REPO_ID = "Qwen/Qwen2.5-7B-Instruct"
# VLLM_COMPLETIONS_URL = "http://192.168.0.106:8000/v1" #pure vllm
# VLLM_COMPLETIONS_URL = "http://192.168.0.106:82/v1" #one-api nginx
VLLM_COMPLETIONS_URL = "http://192.168.0.101:85/v1" #one-api nginx