base_model: Qwen/Qwen2.5-7B

plugins:
  - axolotl.integrations.liger.LigerPlugin
liger_rope: true
liger_rms_norm: true
liger_glu_activation: true
liger_fused_linear_cross_entropy: true

strict: false

chat_template: chatml
datasets:
  - path: allenai/tulu-3-sft-mixture
    type: chat_template
    split: train
    field_messages: messages

dataset_prepared_path: last_run_prepared
#val_set_size: 0.02
output_dir: ./ckpts

sequence_len: 8192
#sample_packing: true
pad_to_sequence_len: true

wandb_project: qwen-2.5-7b-sft
wandb_entity:
wandb_watch:
wandb_name:
wandb_log_model:

gradient_accumulation_steps: 2
micro_batch_size: 8
num_epochs: 1
optimizer: paged_ademamix_8bit
lr_scheduler: cosine
learning_rate: 3.5e-6

train_on_inputs: false
group_by_length: false
bf16: auto
fp16:
tf32: false

gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
early_stopping_patience:
resume_from_checkpoint:
logging_steps: 1
xformers_attention:
flash_attention: true

deepspeed: deepspeed_configs/zero3_bf16.json

warmup_steps: 370
#evals_per_epoch: 4
eval_table_size:
saves_per_epoch: 2
debug:
weight_decay: 0.0
