services:
  axolotl:
    image: axolotlai/axolotl:main-20250126-py3.11-cu124-2.5.1
    container_name: axolotl
    volumes:
      - /home/paul/.cache/huggingface:/root/.cache/huggingface
      - ./configs:/app/configs
      - ../data/output:/app/output
      - /etc/localtime:/etc/localtime:ro
    # ports:
    #   - "7861:7860"
    #   - "8000:8000"
    ipc: host
    tty: true
    shm_size: '16gb'
    stdin_open: true
    command: bash
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: "all"
            capabilities: [gpu]
    restart: unless-stopped
